Basic Python

1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


2. Use .format() to print the following string.

Output should be: The diameter of Earth is 12742 kilometers

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print(f'The diameter of {planet} is {diameter} killometer')

The diameter of Earth is 12742 killometer


3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]['tricky'][3]["target"][3])

hello


NUMPY

In [ ]:
import numpy as np

4.1 create an array of 10 zeros

In [ ]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.2 create an array 10 fives

In [ ]:
array=np.ones(10)*5
print("an array of 10 fives:")
print(array)

an array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5.create an array of all the even integers from 20 to 35

In [ ]:
array=np.arange(20,35,2)
print(" array of all even numbers from 20 to 35")
print(array)

 array of all even numbers from 20 to 35
[20 22 24 26 28 30 32 34]


6.create 3×3 matix with values ranging from 0 to 8

In [ ]:
array=np.arange(0,9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7.concatenate a and b

 a=np.array([1,2,3])

 b=np.array([4,5,6])

In [ ]:
 a=np.array([1,2,3])
 b=np.array([4,5,6])
arr=np.stack((a,b),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


PANDAS

8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd  
data = {'Name': ['a', 'b', 'c'], 'Age': [20, 21, 19]}  
df = pd.DataFrame(data)  
print(df)

  Name  Age
0    a   20
1    b   21
2    c   19


9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:

from datetime import timedelta, date

def daterange(date1, date2):
    for n in range(int ((date2 - date1).days)+1):
        yield date1 + timedelta(n)

start_dt = date(2023, 1, 1)
end_dt = date(2023, 1, 10)
for dt in daterange(start_dt, end_dt):
    print(dt.strftime("%Y-%m-%d"))

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10


10. Create 2D list to DataFrame

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns = ['a', 'b','c'])
print(df)

   a    b   c
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
